### ISSUE TITLE
TK #02 - Subir Breve Informe de Relevamiento del Proyecto

### ISSUE THREAD

**Issue by facumd** [facumd/masc-ispc#3]
_Registrarse cada integrante faltante dentro del repositorio a trabajar_

- Módulo: [Programador Web - TSDWAD - 2022](https://acceso.ispc.edu.ar/course/view.php?id=2417) 
    - Submódulo: [Actividades Integradoras del Módulo](https://acceso.ispc.edu.ar/course/view.php?id=2417&section=5)

Adjuntar el Siguiente Archivo:

[Planilla Propuestas de Proyecto.docx](https://github.com/facumd/masc-ispc/files/11278298/Planilla.Propuestas.de.Proyecto.docx) (Link actualizado)

**Comment by facumd** [comment]
Hecho 👍

**Comment by Ojedajuan** [comment]
Logrado

**Comment by Marialer27** [comment]
Hecho
