### ISSUE TITLE
TK #03 - Revisar documentación IEEE830

### ISSUE THREAD

**Issue by facumd** [facumd/masc-ispc#4]
Asegurarse que esté completa y retomar desde allí para esta nueva etapa seguir documentando los avances.

Ubicada en la carpeta **documentación** del Repositorio: [Link](https://github.com/facumd/masc-ispc/blob/main/documentacion/Documento%20IEEE830.docx.pdf)

**Comment by TamiSorsaburu** [comment]
Hecho
