### ISSUE TITLE
US #02 - Como usuario: quiero que el sitio muestre "Mis Productos" y "Stock Disponible"

### ISSUE THREAD

**Issue by ChRi5714n** [facumd/masc-ispc#7]
Los servicios/obras que he pedido, recibido, y los que se encuentren disponibles para poder ver de manera certera lo que se encuentra en stock y lo adquirido.

**Comment by facumd** [comment]
Issue cerrado porque se realizó sin planeación y sin motivo, por otro integrante que no siguió en el proyecto.
