### ISSUE TITLE
TK #05  - Crear una sección dentro de las subcategorías de artistas para "Mis Productos" y "Stock Disponible"

### ISSUE THREAD

**Issue by ChRi5714n** [facumd/masc-ispc#8]
Que muestre el stock disponible de los productos y/o servicios y agregar en la sección "Usuario" lo que el usuario ha pedido y recibido en un historial.

**Comment by facumd** [comment]
Issue cerrado porque se realizó sin planeación y sin motivo, por otro integrante que no siguió en el proyecto.
